import { useNavigate } from "react-router";
import AdminProductDetails from "@/routes/admin/product/-components/AdminProductDetails";
import type { ProductsRecord } from "pocketbase-types";
import type { OptionsConfig } from "@/types";
import UpdateImages from "@/components/inputs/UpdateImages";
import { useImages } from "@/helpers/images";
import { useMutation } from "@tanstack/react-query";
import { pb } from "@/api/apiClient";
import { toast } from "sonner";
import { extract_message } from "@/helpers/api";

export default function AdminProductNew() {
  // Define a default empty product object for creating a new product
  const newProductDefault: Partial<ProductsRecord<OptionsConfig>> = {
    id: "", // ID will be generated by PocketBase on creation
    name: "",
    description: "",
    price: 0,
    discountPrice: 0,
    quantity: 0,
    category: "",
    options: {},
    images: [],
  };
  const navigate = useNavigate();
  const imageProps = useImages();
  const { mutateAsync } = useMutation({
    mutationFn: (data: FormData) => pb.collection("products").create(data),
    onSuccess: (resp) => {
      navigate(`/admin/product/${resp.id}`, { replace: true });
    },
  });
  const submit = (data: ProductsRecord) => {
    if (!imageProps.newImages || imageProps.newImages.length === 0) {
      toast.error("Please upload at least one image");
      return;
    }

    const formData = new FormData();
    formData.append("name", data.name || "");
    formData.append("description", data.description || "");
    formData.append("price", data.price?.toString() || "0");
    formData.append("discountPrice", data.discountPrice?.toString() || "0");
    formData.append("quantity", data.quantity?.toString() || "0");
    if (data.category) {
      formData.append("category", data.category);
    }
    if (data.options) {
      formData.append("options", JSON.stringify(data.options));
    }

    imageProps.newImages.forEach((file) => {
      formData.append("images", file);
    });

    toast.promise(mutateAsync(formData), {
      loading: "Creating product...",
      success: "Product created successfully!",
      error: extract_message,
    });
  };
  return (
    <div className="container mx-auto py-8">
      <h1 className="text-3xl font-bold mb-6">Add New Product</h1>
      <div className="my-4">
        <UpdateImages {...imageProps} />
      </div>
      <AdminProductDetails item={newProductDefault as any} add addFn={submit} />
    </div>
  );
}
